import {IEntity, IEntityRef} from './obsproject.interface';
import {Time} from '../../../../units/classes/time';

export interface IObsProposal {
  obsProposalEntity: IEntity;
  documentsRef: IEntityRef;
  obsProjectRef: IEntityRef;
  _abstract: string;
  relatedProposals: string;
  previousProposals: string;
  dateReceived: DateReceived;
  cycle: string;
  studentProject: boolean;
  continuation: boolean;
  scientificCategoryCode: string;
  proposalTypeCode: string;
  scientificCategoryString: string;
  proposalTypeString: string;
  keyword?: (string)[] | null;
  keywordCode?: (string)[] | null;
  principalInvestigator: IInvestigator;
  coInvestigator?: (IInvestigator)[] | null;
  proposalFeedback: ProposalFeedback;
  schemaVersion: string;
  revision: string;
  almatype: string;
  scienceGoals?: (ScienceGoalsEntity)[] | null;
  obsPlan: ObsPlan;
}

export interface DateReceived {
  year: number;
  month: number;
  day: number;
  timezone: number;
  hour: number;
  minute: number;
  second: number;
  fractionalSecond: number;
}
export interface IInvestigator {
  fullName: string;
  organisation: string;
  eMail: string;
  verfiedUser: boolean;
  userId: string;
  telephone: string;
  mobile: string;
  index: number;
  organisationId: string;
  allowedExec: string;
  associatedExec: string;
}
export interface ProposalFeedback {
  estimatedTotalIntegrationTime: Time;
  arrayTimeBreakdown: IArrayTimeBreakdown;
  dataRateBreakdown: IDataRateBreakdown;
  receiverTimeBreakdown: IReceiverTimeBreakdown;
  timeAllocationBreakdown: ITimeAllocationBreakdown;
}
export interface EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay {
  value: number;
  unit: string;
}
export interface IArrayTimeBreakdown {
  arrayTime?: (IArrayTime)[] | null;
}
export interface IArrayTime {
  estimatedTime: Time;
  arrayName: string;
}
export interface IDataRateBreakdown {
  arrayDataRates?: (IArrayDataRates)[] | null;
}
export interface IArrayDataRates {
  estimatedAverageDataRate: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  estimatedMaximumDataRate: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  estimatedDataVolume: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  arrayName: string;
}
export interface IReceiverTimeBreakdown {
  receiverTime?: (ReceiverTimeEntity)[] | null;
}
export interface ReceiverTimeEntity {
  time: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  receiverBand: string;
}
export interface ITimeAllocationBreakdown {
  executiveFraction?: (ExecutiveFractionEntity)[] | null;
}
export interface ExecutiveFractionEntity {
  timeFraction: number;
  name: string;
}
export interface ScienceGoalsEntity {
  estimatedTotalTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  userPriority: number;
  requiredReceiverBands?: (string)[] | null;
  estimated12MTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  estimated7MTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  estimatedTPTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  estimatedACATime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  isDescoped: boolean;
  calibrationSetupParameters: CalibrationSetupParameters;
  performanceParameters: PerformanceParameters;
  spectralSetupParameters: SpectralSetupParameters;
  targetParameters?: (TargetParametersEntity)[] | null;
  technicalJustification?: (TechnicalJustificationEntity)[] | null;
  mode: string;
  name: string;
  note: string;
}
export interface CalibrationSetupParameters {
  selection: string;
}
export interface PerformanceParameters {
  desiredAngularResolution: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  desiredLargestScale: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  desiredSensitivity: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  desiredDynamicRange: number;
  representativeFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  useACA: boolean;
  isTimeConstrained: boolean;
  useTP: boolean;
  desiredSDSensitivity: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  isPointSource: boolean;
  desiredSensitivityReferenceFrequencyWidth: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  needsMoreTime: boolean;
  desiredACASensitivity: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  desiredTPSensitivity: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  isScheduleConstrained: boolean;
  desiredTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  desiredSensitivityFrequencyMeasure: string;
}
export interface DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth {
  userUnit: string;
  value: number;
  unit: string;
}
export interface SpectralSetupParameters {
  representativeFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  userRepresentativeFrequency: boolean;
  singleContinuumFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  scienceSpectralWindowOrSpectralScan?: (ScienceSpectralWindowOrSpectralScanEntity)[] | null;
  polarisation: string;
  type: string;
}
export interface ScienceSpectralWindowOrSpectralScanEntity {
  transitionName: string;
  centerFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  bandWidth: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  spectralResolution: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  groupIndex: number;
  isSkyFrequency: boolean;
  splatalogId?: number | null;
  representativeWindow: boolean;
  groupResourceUse: string;
  index: number;
  advancedWindowSetup: AdvancedWindowSetup;
}
export interface AdvancedWindowSetup {
  smoothingFactor: number;
  oversampling: boolean;
  addedSensitivity: boolean;
  useImage: boolean;
  useThis: boolean;
  smoothingFunction: string;
}
export interface TargetParametersEntity {
  isMosaic: boolean;
  circleOrEllipseOrPolygon?: (CircleOrEllipseOrPolygonEntity)[] | null;
  type: string;
  sourceName: string;
  sourceCoordinates: CentreOrSourceCoordinates;
  pmRA: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  pmDec: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  parallax: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  nonSiderealMotion: boolean;
  sourceEphemeris: string;
  sourceVelocity: SourceVelocityOrVelocityResolution;
  index: number;
  expectedProperties: ExpectedProperties;
  solarSystemObject: string;
}
export interface CircleOrEllipseOrPolygonEntity {
  paLong: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  _long: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  _short: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  spacing: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  referenceFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  name: string;
  centre: CentreOrSourceCoordinates;
}
export interface CentreOrSourceCoordinates {
  longitude: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  latitude: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  fieldName: string;
  system: string;
  type: string;
}
export interface SourceVelocityOrVelocityResolution {
  centerVelocity: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  referenceSystem: string;
  dopplerCalcType: string;
}
export interface ExpectedProperties {
  expectedPeakFluxDensity: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  desiredPolarizationPercentage: number;
  expectedLineWidth: DesiredAngularResolutionOrDesiredSensitivityOrDesiredSDSensitivityOrDesiredSensitivityReferenceFrequencyWidthOrDesiredACASensitivityOrDesiredTPSensitivityOrBandWidthOrSpectralResolutionOrSpacingOrExpectedLineWidth;
  referenceFrequency: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  expectedPeakLineFluxDensity: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  expectedSpectralDynamicRange: number;
  expectedImageDynamicRange: number;
  desiredLinePolarizationPercentage: number;
  desiredLineCircularPolarizationPercentage: number;
  desiredCircularPolarizationPercentage: number;
  solarActivityLevel: string;
}
export interface TechnicalJustificationEntity {
  justificationText: string;
  justificationKey: string;
}
export interface ObsPlan {
  scienceProcessingScript: string;
  runSciencePipeline: boolean;
  dataProcessingParameters: DataProcessingParameters;
  flowControl: FlowControl;
  entityPartId: string;
  almatype: string;
  name: string;
  note: string;
  obsUnitControl: ObsUnitControl;
  unitDependencies: UnitDependencies;
  status: string;
}
export interface DataProcessingParameters {
  angularResolution: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  velocityResolution: SourceVelocityOrVelocityResolution;
  tbSensitivityGoal: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  rmsGoal: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  projectType: string;
}
export interface FlowControl {
  controlScript: string;
}
export interface ObsUnitControl {
  calibrationRequirements: CalibrationRequirements;
  maximumTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  userPriority: number;
  estimatedExecutionTime: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  tacPriority: number;
  aggregatedExecutionCount: number;
  arrayRequested: string;
}
export interface CalibrationRequirements {
  pointingAccuracy: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  bandpassAccuracy: number;
  polarizationAccuracy: number;
}
export interface UnitDependencies {
  executionCount: number;
  delay: EstimatedTimeOrEstimatedAverageDataRateOrEstimatedMaximumDataRateOrEstimatedDataVolumeOrTimeOrEstimatedTotalIntegrationTimeOrDesiredLargestScaleOrRepresentativeFrequencyOrDesiredTimeOrCenterFrequencyOrSingleContinuumFrequencyOrLongitudeOrLatitudeOrPaLongOrLongOrShortOrReferenceFrequencyOrCenterVelocityOrExpectedPeakFluxDensityOrExpectedPeakLineFluxDensityOrPmRAOrPmDecOrParallaxOrEstimatedTotalTimeOrEstimated12MTimeOrEstimated7MTimeOrEstimatedTPTimeOrEstimatedACATimeOrAngularResolutionOrTbSensitivityGoalOrRmsGoalOrPointingAccuracyOrMaximumTimeOrEstimatedExecutionTimeOrDelay;
  expression: string;
}
