export interface ISpectralLine {
  line_id;
  species_id;
  s_name_noparens;
  chemical_name;
  orderedfreq;
  resolved_QNs;
  sijmu2;
  E_up_K;
  lovas_int;
  top20;
  planet;
  ism_hotcore;
  ism_diffusecloud;
  comet;
  ism_darkcloud;
  extragalactic;
  agb_ppn_pn;
}
