export enum SolarSystemObjects {
  MERCURY   = 'Mercury',
  VENUS     = 'Venus',
  MOON      = 'Moon',
  MARS      = 'Mars',
  JUPITER   = 'Jupiter',
  SATURN    = 'Saturn',
  URANUS    = 'Uranus',
  NEPTUNE   = 'Neptune',
  PLUTO     = 'Pluto',
  SUN       = 'Sun',
  GANYMEDE  = 'Ganymede',
  EUROPA    = 'Europa',
  CALLISTO  = 'Callisto',
  IO        = 'Io',
  TITAN     = 'Titan',
  CERES     = 'Ceres',
  PALLAS    = 'Pallas',
  JUNO      = 'Juno',
  VESTA     = 'Vesta',
  EPHEMERIS = 'Ephemeris'
}
